export const SocietyRegistration = {
    "mTypes": [
        { id: 1, position: "President" },
        { id: 2, position: "Secretary" },
        { id: 3, position: "Treasurer" },
        { id: 4, position: "Owner" },
        { id: 5, position: "Tenant" },
    ],
    "blockNo": [
        {blockSequ: 1, blockName: 'A1'},
        {blockSequ: 2, blockName: 'A2'},
        {blockSequ: 3, blockName: 'A3'},
        {blockSequ: 4, blockName: 'A4'}
    ],
    "wing": [
        {wingSequ: 1, wingName: 'A'},
        {wingSequ: 2, wingName: 'B'},
        {wingSequ: 3, wingName: 'C'},
        {wingSequ: 4, wingName: 'D'},
        {wingSequ: 5, wingName: 'E'},
        {wingSequ: 6, wingName: 'F'},
        {wingSequ: 7, wingName: 'G'},
        {wingSequ: 8, wingName: 'H'},
        {wingSequ: 9, wingName: 'I'},
        {wingSequ: 10, wingName: 'J'},
    ],
    "floor": [
        {floorSequ: 1, floorName: '1st'},
        {floorSequ: 2, floorName: '2nd'},
        {floorSequ: 3, floorName: '3rd'},
        {floorSequ: 4, floorName: '4th'},
        {floorSequ: 5, floorName: '5th'},
        {floorSequ: 6, floorName: '6th'},
        {floorSequ: 7, floorName: '7th'},
        {floorSequ: 8, floorName: '8th'},
        {floorSequ: 9, floorName: '9th'},
        {floorSequ: 10, floorName: '10th'},
        {floorSequ: 11, floorName: '11th'},
        {floorSequ: 12, floorName: '12th'},
        {floorSequ: 13, floorName: '13th'},
        {floorSequ: 14, floorName: '14th'},
        {floorSequ: 15, floorName: '15th'},
        {floorSequ: 16, floorName: '16th'},
        {floorSequ: 17, floorName: '17th'},
        {floorSequ: 18, floorName: '18th'},
        {floorSequ: 19, floorName: '19th'},
        {floorSequ: 20, floorName: '20th'},
        {floorSequ: 21, floorName: '21st'},
        {floorSequ: 22, floorName: '22nd'},
        {floorSequ: 23, floorName: '23rd'},
        {floorSequ: 24, floorName: '24th'},
        {floorSequ: 25, floorName: '25th'},
    ]
}