export const Labels = {
  movementkyc: {
    agentInfo: "Agent Info",
    agentCodeSearch: "Agent Code Search",
    personal: "Personal",
    supervisor: "Supervisor",
    office: "Office",
    mentor: "Mentor",

    movementHistory: "Movement History",
    transaction: "Movement Type",
    reason: "Movement Reason",
    effective: "Effective",
    creater: "Creater",
    approver: "Approver",

    portfolio: "Portfolio",
    policyno: "Policy No",
    policyHolder: "Policy Holder",
    riskCommencementDate: "Risk Commencement Date",
    servicingFromDate: "Servicing from Date",
    servicingtoDate: "Servicing To Date",
    businessSource: "Business Source",
    originalWritingAgent: "Original Writing Agent",

    directReportees: "Direct Reportees",
    code: "Code",
    name: "Name",
    designation: "Designation",
    status: "Status",
    from: "From",
    reporteeoffice: "Office",

    monitoringStaff: "Monitoring Staff",
    staffcode: "Code",
    staffName: "Name",
    staffDesignation: "Designation",
    staffStatus: "Status",
    staffFrom: "From",
    staffOffice: "Office",

    protegees: "Protégées",
    proCode: "Code",
    proName: "Name",
    proDesigantion: "Designation",
    proStatus: "Status",
    proFrom: "From",
    proOffice: "Office"
  },
  agentMovement: {
    agentMovementTitle: "Movement Details",

    effectiveDate: "Effective From Date",
    reason: "Movement Reason",
    designation: "New Designation",
    jobTitle: "Job Title",
    supervisorSearch: "New Supervisor Code",
    mentorSearch: "New Mentor Code",
    monitoringSearch: "New Monitoring Code",
    branchSearch: "New Branch Code",
    portfolioOwnership: "Portfolio Ownership",
    subordinateOwnership: "Subordinate Ownership",
    monitoringOwnership: "Monitoring Ownership",
    protegeesOwnership:"Protégées Ownership"
  },
  fileUploadDownload: {
    uploadTemplate: 'Upload Template',
    totalRecords: 'Total Records',
    successRecords: 'Success Records',
    rejectedRecords: 'Rejected Records',
    fromTo: 'From - To'
  },
  masterConfiguration: {
    pageHeader: 'Master',
    btnSave: 'Save',
    btnClose: 'Close',
  },
  reportingLinks: {
    screenTitle: 'Reporting Links',
    ddlChannelCode: 'Channel Code',
    txtReportingLinkCode: 'Reporting Link Code',
    txtReportingLinkDesc: 'Reporting Link Description',
    btnAddMoreHierarchies: 'Add More',
    ddlDesignation: 'Designation',
    txtTier: 'Tier',
    btnSaveReportingLink: 'Save',
    btnNewReportingLink: 'New',
    btnSendForApproval: 'Send For Approval',
    btnApprove: 'Approve',
    btnLaunchChannel: 'Launch'
  },
  hierarchyDetails: {
    screenTitle: 'Hierarchy',
    txtChannel: 'Channel',
    txtParentEntity: 'Parent Entity',
    ddlEntityType: 'Entity Type',
    txtMntManager: 'Monitoring Manager',
    btnEntityHierarchyNext: 'Next'
  },
  entityDetails: {
    screenTitle: 'Entity Information',
    identitySection: 'Identity',
    txtEntityName: 'Entity Name',
    ddlIdentityType: 'Identity Type',
    txtIdentityInfo: 'Identity Information',
    btnIdentityNext: 'Next',

    addressSection: 'Address',
    txtAddrLine1: 'Address Line 1',
    txtAddrLine2: 'Address Line 2',
    txtLocality: 'Locality',
    txtCity: 'City',
    txtDistrict: 'District',
    txtState: 'State',
    txtPinCode: 'Pincode',
    ddlCountry: 'Country',
    btnAddUpdateAddr: 'Add/Update',
    btnClearAddr: 'Clear',
    primAddr: 'Set As Primary?',
    btnAddressNext: 'Next',

    contactSection: 'Contact Details',
    txtMobileNo: 'Mobile Number',
    btnAddUpdateMobile: 'Add/Update',
    btnClearMobile: 'Clear',
    mobileHeader: 'Mobile:',
    primMob: 'Set As Primary?',

    txtEmailId: 'Email Address',
    btnAddUpdateEmail: 'Add/Update',
    btnClearEmail: 'Clear',
    btnContactNext: 'Next',

    licenseSection: 'License Details',
    ddlInsuranceTypes: 'Insurance Types',
    ddlLifeInsurers: 'Life Insurer',
    ddlNonLifeInsurers: 'Non-Life Insurer',
    txtURNNumber: 'IRDAI URN',
    txtLicenseNo: 'License No',
    dtFromDate: 'From Date',
    dtToDate: 'To Date',
    dtFromToDateRange: 'From - To',
    btnAddUpdateLicense: 'Add/Update',
    btnUpdateLicense:'Update',
    btnClearLicense: 'Clear',
    btnLicenseNext: 'Next'
  },
  entityAssessment: {
    screenTitle: 'Assessment',
    questionsNotSetup: 'Questionnaire is not applicable for the applicant, please click on Next to proceed.',
    btnAssessmentNext: 'Next'
  },
  entityRequirements: {
    screenTitle: 'Documents',
    ddlDocType: 'Document Type',
    fileUpdCtrl: 'Upload Files',
    lblRemarks: 'Remarks',
    btnRequirementNext: 'Next',
    btnSave:'Save'
  },
  entityPayment: {
    screenTitle: 'Payment',
    ddlPayTo: 'Pay To',
    bankDetailsSection: 'Bank Details',
    txtEntityName: 'Entity Name',
    txtAccountNo: 'Account Number',
    txtBankName: 'Name of Bank',
    ddlBranchName: 'Choose Your Branch Name',
    txtIfsc: 'IFSC Code',
    txtMicr: 'MICR Code',
    btnBankNext: 'Next',
    minAmtDetailSection: 'Minimum Amount Detail',
    txtMinAmt: 'Minimum Amount',
    txtOvrMinAmt: 'Overriden Minimum Amount',
    dtFromDate: 'From Date',
    dtToDate: 'To Date',
    dtFromToDateRange: 'From - To',
    btnMinAmtSave: 'Save'
  },
  entityListing: {
    screenTitle: 'Entity Listing',
    btnBlkPrcEntity: 'Bulk Processing',
    btnNewEntity: 'New Entity',
    btnApply: 'Apply',
    btnClear: 'Clear',
    channelFilterAcc: 'Channel',
    candidateFilterAcc: 'Entity',
    txtEntityName: 'Entity Name',
    txtSearchFilter: 'Search',
    tblColCode: 'Code',
    tblColName: 'Name',
    tblColChannel: 'Channel',
    tblColJobTitle: 'Job Title',
    tblColMntMgr: 'Monitoring Manager',
    tblColStatus: 'Status',
    tblColAddress: 'Address',
    tblNoRecordsFound: 'No Records Found'
  },
  entityProcessing: {
    screenTitle: 'Entity Processing',
    btnBlkPrcEntity: 'Bulk Processing',
    btnNewEntity: 'New Entity',
    btnApply: 'Apply',
    btnClear: 'Clear',
    channelFilterAcc: 'Channel',
    candidateFilterAcc: 'Entity',
    txtEntityName: 'Entity Name',
    txtSearchFilter: 'Search',
    tblColCode: 'Code',
    tblColName: 'Name',
    tblColChannel: 'Channel',
    tblColJobTitle: 'Job Title',
    tblColMntMgr: 'Monitoring Manager',
    tblColStatus: 'Status',
    tblColAddress: 'Address',
    tblNoRecordsFound: 'No Records Found'
  },
  movementPortfolo:{
    portfolioOwnership: "Portfolio Ownership",
    subordinateOwnership: "Subordinate Ownership",
    monitoringOwnership: "Monitoring Ownership",
    protegeesOwnership:"Protégées Ownership",
    ProtegeesHeader:"Protégées"
  }
};
